fixes #32494 - Removing fact parser
theforeman/foreman_ansible pull request #408
Opened 2021-05-03 14:13 UTC by domitea

Removing fact parser according to moving them to core

This a plugin part of https://github.com/theforeman/foreman/pull/8491 PR where I add a Ansible parser to core.

2021-06-16 11:12 UTC, tbrisker commented
This is missing dropping of the AnsibleFactParser itself

2021-06-16 11:23 UTC, tbrisker requested changes
We should also update the minimal foreman version and drop the legacy non-structured fact importer

2021-06-16 11:23 UTC, tbrisker commented on lib/foreman_ansible/engine.rb
>          ::Foreman::Plugin.fact_importer_registry.register(:ansible, ForemanAnsible::FactImporter)
I'm pretty sure we can drop this as well, foreman_ansible requires a much newer foreman already

2021-06-23 07:47 UTC, tbrisker commented on lib/foreman_ansible/register.rb
> +  requires_foreman '>= 2.5'
I think this should be 2.6, since the parser was only recently merged in core

2021-06-23 08:11 UTC, ezr-ondrej commented
[test foreman_ansible]

2021-07-08 08:22 UTC, tbrisker commented
[test foreman_ansible]

2021-07-08 10:40 UTC, ezr-ondrej approved these changes
Jenkins is broken, but GH actions approves.
@adamruzicka anything to add here?

2021-07-08 12:51 UTC, adamruzicka requested changes
Could you also go through `.rubocop_todo.yml` and drop the no-longer-relevant lines from there?

2021-07-08 14:58 UTC, tbrisker commented
[test foreman_ansible] now lets see if the fix in core worked...

2021-07-08 16:12 UTC, tbrisker commented
Perhaps this pr needs a rebase?
```
LoadError: cannot load such file -- foreman_tasks_core
/usr/local/rvm/gems/ruby-2.7.0@foreman_ansible-pull-request-1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.7.0@foreman_ansible-pull-request-1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.7.0@foreman_ansible-pull-request-1/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `block in require'
/usr/local/rvm/gems/ruby-2.7.0@foreman_ansible-pull-request-1/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/rvm/gems/ruby-2.7.0@foreman_ansible-pull-request-1/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `require'
/home/jenkins/workspace/foreman_ansible-pull-request/database/postgresql/label/fast/ruby/2.7/plugin/lib/foreman_ansible_core.rb:3:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.7.0@foreman_ansible-pull-request-1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.7.0@foreman_ansible-pull-request-1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.7.0@foreman_ansible-pull-request-1/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `block in require'
/usr/local/rvm/gems/ruby-2.7.0@foreman_ansible-pull-request-1/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/rvm/gems/ruby-2.7.0@foreman_ansible-pull-request-1/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `require'
/home/jenkins/workspace/foreman_ansible-pull-request/database/postgresql/label/fast/ruby/2.7/plugin/lib/foreman_ansible/engine.rb:7:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.7.0@foreman_ansible-pull-request-1/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `require'
/usr/local/rvm/gems/ruby-2.7.0@foreman_ansible-pull-request-1/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `block in require'
/usr/local/rvm/gems/ruby-2.7.0@foreman_ansible-pull-request-1/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/rvm/gems/ruby-2.7.0@foreman_ansible-pull-request-1/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `require'
/home/jenkins/workspace/foreman_ansible-pull-request/database/postgresql/label/fast/ruby/2.7/plugin/lib/foreman_ansible.rb:4:in `<top (required)>'

2021-07-09 10:20 UTC, ezr-ondrej commented
[test foreman_ansible]

2021-07-09 12:09 UTC, ezr-ondrej commented
Yeap, rebase would help, I'd merge without it, but Adam's point is valid, no reason to keep the lines in `.rubocop_todo.yml`

2021-07-13 07:55 UTC, tbrisker commented
[test foreman_ansible] Should be green now, the issue in rex was fixed in https://github.com/theforeman/foreman_remote_execution/commit/e492aef4b0de384011990b7ddb28447dd3d3c8bf
GH actions tests should be fixed by https://github.com/theforeman/foreman_ansible/pull/430

2021-07-13 08:16 UTC, tbrisker approved these changes
Thanks @domitea, test failures are unrelated, lets get this in.

2021-07-13 08:17 UTC, merged