Fixes #33840 - Add pagination to all roles modal
theforeman/foreman_ansible pull request #480
Opened 2021-11-03 07:58 UTC by xprazak2

2021-11-03 20:18 UTC, amirfefer requested changes
Thanks @xprazak2 👍 overall works well

a page transition creates a loading state for the entire page instead of just the table:
https://user-images.githubusercontent.com/11807069/140185745-2e0815b0-5f67-460c-87b4-28e8ce55baee.mov

same in modal, also a fixed hight value can prevent the modal's size change while loading:
https://user-images.githubusercontent.com/11807069/140185956-3452bfc1-c2af-453c-99fb-49b0adc35ad6.mov

2021-11-04 07:20 UTC, xprazak2 commented on webpack/components/AnsibleHostDetail/components/RolesTab/AllRolesModal/AllRolesTable.js
> +          {allAnsibleRoles.map(role => (
Which values should I extract?

2021-11-04 07:22 UTC, xprazak2 commented
Thank you for review & testing @amirfefer! Any suggestions to what height the modal size should be fixed?

Scope here is just to add pagination into modal, I can adjust the loading states as a follow-up (since that will be probably same for all the tables) if that is something we want.

2021-11-04 15:45 UTC, amirfefer commented
PF design [documentation](https://www.patternfly.org/v4/components/modal/design-guidelines) doesn't mention fixed height for modals, @MariSvirik, any idea?

2021-11-04 15:46 UTC, amirfefer commented on webpack/components/AnsibleHostDetail/components/RolesTab/AllRolesModal/AllRolesTable.js
> +          {allAnsibleRoles.map(role => (
{id, name, inherited }

2021-11-07 16:16 UTC, amirfefer approved these changes
let's fix the loading and css in a follow-up PR :), the pagination itself works as expected

2021-11-09 12:35 UTC, ezr-ondrej approved these changes
Thanks @xprazak2 and @amirfefer ! :+1:

2021-11-09 12:35 UTC, merged