Fixes #35100 - disable submit if no changes in roles edit
theforeman/foreman_ansible pull request #537
Opened 2022-06-23 12:52 UTC by Ron-Lavi

also adjusting the edit roles modal's width to 50% instead of 70%

2022-06-29 14:09 UTC, stejskalleos commented on webpack/components/AnsibleHostDetail/components/RolesTab/EditRolesModal/EditRolesForm.js
> +      isDisabled={loading || isEqual(initAvailableOptions, availableOptions)}
For me button is still enabled, steps to reproduce:
* (host without any assigned roles)
* Show modal => button is disabled :heavy_check_mark: 
* Select role(s) => button is enabled :heavy_check_mark: 
* Remove all assigned roles => button is enabled  :x:

2022-06-30 05:56 UTC, stejskalleos commented on webpack/components/AnsibleHostDetail/components/RolesTab/EditRolesModal/EditRolesForm.js
> +      isDisabled={loading || isEqual(initAvailableOptions, availableOptions)}
Yop, here it is:

https://user-images.githubusercontent.com/59385976/176603099-8252d8c8-a26a-47da-a024-8d035dbea97a.mp4

2022-07-04 08:26 UTC, stejskalleos requested changes
Found another issue:
* Assign three roles to the host and save
* Go back to Edit roles modal
* Change order of assigned roles >> Button is still disabled

2022-07-04 17:07 UTC, Ron-Lavi commented
Thanks for double-checking @stejskalleos !
can you try again?

2022-07-07 08:49 UTC, stejskalleos approved these changes
:green_apple: **LGTM**, works as expected.
Thanks @Ron-Lavi !

2022-07-07 08:49 UTC, merged