Fixes #35143 - Add a smart proxy update button
theforeman/foreman_ansible pull request #539
Opened 2022-07-07 13:35 UTC by adamruzicka

Requires:
- https://github.com/theforeman/foreman/pull/9290

2022-09-29 13:19 UTC, stejskalleos requested changes
I tried to run playbook on `3.4` version and got following error:

```
TASK [Update foreman repositories] *********************************************
fatal: [proxy34.example.com]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible_distribution_major_verison' is undefined\n\nThe error appears to be in '/tmp/d20220929-12467-ayq1wo/project/playbook.yml': line 15, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Update foreman repositories\n      ^ here\n"}
```

```bash
ansible --version

ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
```

2022-09-29 13:19 UTC, stejskalleos commented on app/views/foreman_ansible/job_templates/capsule_upgrade_-_ansible_default.erb
> +<% else %>
<% else -%>

2022-10-03 06:55 UTC, stejskalleos commented on app/helpers/foreman_ansible/smart_proxies_helper.rb
> +      ::SmartProxiesController.allocate.send(:versions_mismatched?, version)
IMO we should display the update button only if foreman version > proxy version, it doesn't make sense to display it in opposite case.

2022-10-03 07:53 UTC, stejskalleos commented
I hit another issue: I have two proxies, one of them is not available. If you try to access `/smart_proxies`, you end up in never ending loop.

2022-10-03 09:18 UTC, adamruzicka commented
> I hit another issue: I have two proxies, one of them is not available. If you try to access `/smart_proxies`, you end up in never ending loop.

I'm unable to reproduce that.

2022-10-03 09:26 UTC, adamruzicka commented on app/helpers/foreman_ansible/smart_proxies_helper.rb
> +      # TODO: Extract this into a service in Foreman
Not relevant anymore

2022-10-03 09:26 UTC, adamruzicka commented on app/helpers/foreman_ansible/smart_proxies_helper.rb
> +      ::SmartProxiesController.allocate.send(:versions_mismatched?, version)
Done

2022-10-03 13:10 UTC, adamruzicka commented
> Job is running for proxy34.example.com

That depends on how the mapping between smart proxies and hosts is set up. The installer usually takes care of this, what does `proxy.infrastructure_host_facets` give you?

> We can have multiple proxies on one host?

Yes and no. Manually you can do almost anything. Barring that, at least the data model allows you to treat a single smart proxy as multiple hosts.

And in general, using capsule in upstream setting is probably wrong.

2022-10-04 12:34 UTC, stejskalleos requested changes

2022-10-04 12:34 UTC, stejskalleos commented on app/views/foreman_ansible/job_templates/capsule_upgrade_-_ansible_default.erb
> +        name: https://yum.theforeman.org/releases/{{ foreman_release_version }}/el{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/foreman-release.rpm
On RHEL 8 this is failing on:
```
TASK [Update foreman repositories] *********************************************
  21:
fatal: [proxy33.example.com]: FAILED! => {"changed": false, "msg": "Failed to validate GPG signature for foreman-release-3.4.0-1.el8.noarch: Public key for foreman-release3o_lm6dt.rpm is not installed"}
  22:
PLAY RECAP ***
```

However if I run command manually it works without any problems:
```bash
dnf -y install https://yum.theforeman.org/releases/3.4/el8/x86_64/foreman-release.rpm
```

Little rewrite of playbook helped, but I guess it's not the way we wan't to go:
```yaml
    - name: Update foreman repositories
      yum:
        name: https://yum.theforeman.org/releases/{{ foreman_release_version }}/el{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/foreman-release.rpm
        disable_gpg_check: yes
        state: present
```

2022-10-04 12:35 UTC, stejskalleos commented on app/views/foreman_ansible/job_templates/capsule_upgrade_-_ansible_default.erb
> +        shell: satellite-maintain upgrade run --assumeyes --target-version={{ satellite_version }} <%= whitelist_option %>
Note to myself: test it on latest satellite and older capsule as well

2022-10-12 15:13 UTC, stejskalleos commented
Failing tests have been fixed in https://github.com/theforeman/foreman_ansible/commit/50c6d566c4cc80ec78184f0f809a19a53eb9aa9d, can you rebase please?

Otherwise :green_apple: **LGTM** :green_apple:, template works correctly, proxy have been successfully updated and everything seems to be working.

Just only one little thing to think about - after clicking on _upgrade_ button job invocation is immediately started,
without any option to check the data before starting the upgrade.
That's fine when users are upgrading proxies with N-1 version, but what about users that have proxy two or more versions behind? For them it can be useful to specify different version than the actual one.
I guess it's edge scenario, definitively not blocking this PR, but I'll bet sooner or later someone will point it out and we'll have to do something with it.

2022-10-12 17:48 UTC, adamruzicka commented
Rebased and it should now go through the form instead of being kicked off immediately

2022-10-19 11:17 UTC, stejskalleos commented
:green_apple: **LGTM** Works well, proxy upgrades went smoothly, tests are locally passing so let's get this in!

Thanks @adamruzicka !

2022-10-19 11:17 UTC, merged