Fixes #35100 - disable submit if no changes in roles edit
theforeman/foreman_ansible pull request #543
Opened 2022-07-13 10:36 UTC by Ron-Lavi

2022-07-14 07:00 UTC, Ron-Lavi commented
@stejskalleos JS & Ruby tests are green now

2022-07-14 07:57 UTC, stejskalleos requested changes
On Foreman 3.3 it doesn't work for me,
I'm getting error on Host > Ansible roles page:
```
Error!
Field 'ansibleVariables' doesn't exist on type 'AnsibleRole'
```

2022-07-14 07:57 UTC, stejskalleos commented on foreman_ansible.gemspec
> +  s.add_dependency 'foreman_remote_execution', '~> 7.0.0'
I really hope we won't break anything with this

2022-07-14 07:57 UTC, stejskalleos commented on .github/workflows/js_tests.yml
> +          ref: 3.3-stable
Awesome, it's nice to have green tests for cherry-picks too!

2022-07-14 17:55 UTC, Ron-Lavi commented
@stejskalleos reordered the commits and changed the message of the last one,
ready for another round

2022-07-15 10:51 UTC, stejskalleos approved these changes
:green_apple:  **LGTM**

Thanks @Ron-Lavi, it's great improvement for `7.1-stable`

2022-07-15 10:52 UTC, merged

2022-07-15 11:06 UTC, stejskalleos commented
Released in 7.1.1: https://github.com/theforeman/foreman_ansible/releases/tag/v7.1.1
RPM: https://github.com/theforeman/foreman-packaging/pull/8229
DEB: https://github.com/theforeman/foreman-packaging/pull/8230