Fixes #37342 - Update foreman docs and fix specify matcher documentation
theforeman/foreman_ansible pull request #711
Opened 2024-04-12 11:13 UTC by girijaasoni

Foreman documentation was outdated and using theforeman.org. This PR updates the doc links according to 'https://docs.theforeman.org/nightly/Managing_Configurations_Ansible/index-foreman-el.html'

It also fixes the misdirected redirect for SpecifyMatchers as reported in https://issues.redhat.com/browse/SAT-24111

Note: This Pr is blocked by https://github.com/RedHatSatellite/foreman_theme_satellite/pull/45

2024-04-12 11:28 UTC, ekohl requested changes
Please use the proper APIs. Since https://github.com/theforeman/foreman/commit/b566ea8ab3c56f79edb0ed9a1caa3c28038af961 it's no longer needed to override the root URL isn't because it's creating broken links.

You should be able to use `type: 'docs'` and get the right base URL (including version) and filename.

2024-04-12 11:28 UTC, ekohl commented on app/helpers/foreman_ansible/ansible_plugin_helper.rb
> +      'https://docs.theforeman.org/nightly/Managing_Configurations_Ansible/index-foreman-el.html'
Never hardcode versions.

2024-04-16 07:33 UTC, girijaasoni commented on app/helpers/foreman_ansible/ansible_plugin_helper.rb
> +      'https://docs.theforeman.org/nightly/Managing_Configurations_Ansible/index-foreman-el.html'
ack

2024-06-26 08:15 UTC, ShimShtein requested changes
You can use `documentation_button` and `documentation_url` helpers directly, or wrap them with ansible-specific wrapper to make the code a bit more DRY.

The `documentation_url` helper [calls](https://github.com/theforeman/foreman/blob/e9891a9e3292e6755113164edd7c1d8dbb4648de/app/helpers/application_helper.rb#L326) the [`links_controller`](https://github.com/theforeman/foreman/blob/e9891a9e3292e6755113164edd7c1d8dbb4648de/app/controllers/links_controller.rb#L10C7-L10C19) under the hood. In our case we want the `docs` type of link with its relevant parameters. This will also enable proper branding down the line.

2024-06-26 13:22 UTC, ekohl commented on app/views/ansible_roles/index.html.erb
> + documentation_button('#Importing_Ansible_Roles_and_Variables_ansible', :root_url => ansible_doc_url) %>
I'm not sure you can pass a position argument in the middle. It's probably
```suggestion
  documentation_button('Managing_Configurations_Ansible', type: 'docs', chapter: 'Importing_Ansible_Roles_and_Variables_ansible') %>
```

2024-06-27 06:53 UTC, ShimShtein commented on app/views/ansible_roles/index.html.erb
> + documentation_button('#Importing_Ansible_Roles_and_Variables_ansible', :root_url => ansible_doc_url) %>
Yup, makes sense. Hope it wasn't too confusing

2024-07-22 13:53 UTC, ekohl commented
@girijaasoni any update on this?

2024-07-26 10:28 UTC, girijaasoni commented
> @girijaasoni any update on this?

almost done, confused about this [comment](https://github.com/RedHatSatellite/foreman_theme_satellite/pull/45#pullrequestreview-2141713392) , should I update it in accordance with 6.15?

2024-07-26 11:35 UTC, ekohl requested changes

2024-07-26 11:35 UTC, ekohl commented on app/views/ansible_variables/_fields.erb
> +      <h2><%= _("Specify Matchers") %>  <%= documentation_button('Managing_Configurations_Ansible', type: 'docs', chapter: 'Overriding_Ansible_Variables_in_foreman_ansible') %></h2>
```suggestion
      <h2><%= _("Specify Matchers") %>  <%= documentation_button('Managing_Configurations_Ansible', type: 'docs', chapter: 'Overriding_Ansible_Variables_in_foreman_ansible') %></h2>
```

2024-07-26 11:35 UTC, ekohl commented on app/views/ansible_roles/welcome.html.erb
> +  <p><%= link_to(_('Learn more about this in the documentation.'), documentation_url('Managing_Configurations_Ansible', type: 'docs',  chapter: 'Importing_Ansible_Roles_and_Variables_ansible'), targe
```suggestion
  <p><%= link_to(_('Learn more about this in the documentation.'), documentation_url('Managing_Configurations_Ansible', type: 'docs',  chapter: 'Importing_Ansible_Roles_and_Variables_ansible'), target: '_blank') %></p>
```

2024-07-31 13:40 UTC, stejskalleos approved these changes

2024-07-31 13:41 UTC, merged

2024-07-31 13:42 UTC, stejskalleos commented
Thanks @girijaasoni @ekohl

2024-07-31 19:02 UTC, Odilhao commented
@stejskalleos can we get this cherrypick 13.0.z?