Adding Ansible Check Mode to Ansible Job Templates
theforeman/foreman_ansible pull request #742
Opened 2024-10-22 23:50 UTC by bnerickson

#### Overview of Changes
This PR intends to add the Ansible Check Mode (identified with the --check argument) to Ansible Job Templates via a checkbox option.  The follow-up after all the subsequent PRs are submitted/approved (hammer cli support for instance) is to add Ansible Diff Mode support in a similar manner.  See below screenshot:

![screenshot](https://github.com/user-attachments/assets/6129ed6a-a9cf-4251-8b76-b6e8bc86aa40)

#### Implementation Considerations
Foreman already offers the ability for users to run Ansible Config Commands with check mode enabled by setting the host's host parameter ansible_roles_check_mode to True.  This is left in-place as-is.  However, adding the ability to craft Job Templates with check mode enabled affords greater flexibility by allowing scheduling of Ansible Jobs with check mode enabled across any number of hosts without needing to remember to set or clear a host parameter.

I have a few questions/concerns:
1. I believe [this change](https://github.com/theforeman/smart_proxy_ansible/pull/48/commits/c5df4e07bb9c03b1e725a96b84d72a53f1656ec9#diff-65b556454b9717ae33c08487e6ace03409dadb3c66b54f921b1dee1caccfb142R189) in https://github.com/theforeman/smart_proxy_ansible/pull/48 should be reverted if this PR is approved.  IMO, the ansible_roles_check_mode parameter _should_ enable check mode for all Ansible jobs, rex (remote execution) or not.  If a user wishes to only run with check mode enabled on specific jobs, then they can unset ansible_roles_check_mode and create custom jobs with check mode enabled.  If this is agreed upon, I can submit a PR to revert and mark it as a dependency on this PR.
2. For the [db/migrate/20241022000000_add_ansible_check_mode_to_templates.rb](https://github.com/theforeman/foreman_ansible/compare/master...bnerickson:foreman_ansible:check-mode-flag?expand=1#diff-0478c1f4badadd851533896cbc75394aab608daff65c13b1c0259444b8c938dc) file, I arbitrarily set the date string in the filename to 20241022000000, but is that supposed to be automatically generated somehow?

#### Testing Steps
- What steps should reviewers follow to test this PR? 

#### Checklists

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman/blob/develop/CONTRIBUTING.md) guidelines.
* [x] I have added relevant tests for my changes.
* [ ] I have updated the documentation accordingly.

#### Additional Notes
[ ] Pending hammer-cli PR
[ ] Pending smart_proxy_ansible PR?

2024-10-23 10:24 UTC, adamruzicka commented
Would it also make sense to have this on the job level?

2024-10-23 16:54 UTC, bnerickson commented
> Would it also make sense to have this on the job level?

Agreed!  It'd be great if this were also available on a job-based level.  I might tackle that after job templates are working.  I don't know where to start there yet.

2024-10-24 06:42 UTC, maximiliankolb commented
cc @Thorben-D

2024-12-25 16:03 UTC, nofaralfasi requested changes
I'm currently facing some issues with my local environment, so I'll need to delay testing until they're resolved. In the meantime, to answer your question:

> For the [db/migrate/20241022000000_add_ansible_check_mode_to_templates.rb](https://github.com/theforeman/foreman_ansible/compare/master...bnerickson:foreman_ansible:check-mode-flag?expand=1#diff-0478c1f4badadd851533896cbc75394aab608daff65c13b1c0259444b8c938dc) file, I arbitrarily set the date string in the filename to 20241022000000, but is that supposed to be automatically generated somehow?

Yes. If you run the Rails generator command to create a migration (`rails generate migration`), Rails automatically prefixes the migration file name with the appropriate timestamp. 
As long as the timestamp doesn't conflict with existing migration timestamps, it's fine to proceed with the manually set value.

2025-01-03 18:53 UTC, bnerickson commented on db/migrate/20241022000000_add_ansible_check_mode_to_templates.rb
> +# frozen_string_literal: true
@nofaralfasi removed in latest commit

2025-01-03 18:53 UTC, bnerickson commented on db/migrate/20241022000000_add_ansible_check_mode_to_templates.rb
> +class AddAnsibleCheckModeToTemplates < ActiveRecord::Migration[6.0]
@nofaralfasi updated to 7.0 in latest commit

2025-01-03 18:54 UTC, bnerickson commented on db/migrate/20241022000000_add_ansible_check_mode_to_templates.rb
> +    end
@nofaralfasi removed in latest commit.

2025-01-22 15:52 UTC, nofaralfasi approved these changes

2025-02-17 16:30 UTC, merged

2025-02-17 16:31 UTC, nofaralfasi commented
Thank you @bnerickson!